[tool.poetry]
name = "stepanenkoartem_brain_games"
version = "0.2.1"
description = "First Hexlet Python Project"
authors = ["Artem Stepanenko <artem.stepanenko.ks.ua@gmail.com>"]

packages = [
        {include = "brain_games" },
        ]

[tool.poetry.dependencies]
python = "^3.7"
prompt = "^0.4.1"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"

[[tool.poetry.source]]
name = "stepanenkoartem-brain-games"
url = "https://test.pypi.org/simple/"

[tool.poetry.scripts]
  brain-games = "brain_games.scripts.brain_game:main"
  brain-even = "brain_games.scripts.brain_even:main"
  brain-calc = "brain_games.scripts.brain_calc:main"
  brain-gcd = "brain_games.scripts.brain_gcd:main"
  brain-progression = "brain_games.scripts.brain_progression:main"
  brain-prime = "brain_games.scripts.brain_prime:main"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

